### PR TITLE
Add option to choose the lib type (shared or static)

### PR DESCRIPTION
**Pull request by WilliamTambellini**
Add a lib_type build option.
Fixing linking failure with libbenchmark 1.7 (could need pthreads)

### CODE REVIEW

**Review by matiaslin — COMMENTED** [review]
Having this added flexibility to the library type sounds like a great idea to me.

**Review by r-devulap — APPROVED** [review]
LGTM. Will let the Ci pass before merging. Might be useful to have one of the CI tests build with the new option.

**Comment by r-devulap** [comment]
Closes #161 and #163

**Comment by r-devulap** [comment]
Thanks @WilliamTambellini!

**Pull request merged**
